### ISSUE TITLE
CLI 创建的项目无法正常运行

### ISSUE THREAD

**Issue by Air1996** [NWYLZW/qq-guild-sdk#6]
node version 18.3.0
@qq-guild-sdk/core version: 2.1.4

报错信息:
$ yarn dev       
yarn run v1.22.19
$ ts-node -r dotenv/config src/index.ts
/SOME_PROJECT_DIR/node_modules/@qq-guild-sdk/core/dist/index.cjs:402
    super((resolve, reject) => {
    ^
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at /SOME_PROJECT_DIR/node_modules/@qq-guild-sdk/core/dist/index.cjs:403:7
    at new Promise (<anonymous>)
    at new Future (/SOME_PROJECT_DIR/node_modules/@qq-guild-sdk/core/dist/index.cjs:402:5)
    at /SOME_PROJECT_DIR/node_modules/@qq-guild-sdk/core/dist/index.cjs:545:30
    at new Promise (<anonymous>)
    at Proxy.startClient (/SOME_PROJECT_DIR/node_modules/@qq-guild-sdk/core/dist/index.cjs:539:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/SOME_PROJECT_DIR/src/index.ts:18:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by NWYLZW** [comment]
是我为了自动重连而引入的问题，我今天会试着修复一下这个问题

谢谢反馈

**Comment by NWYLZW** [comment]
应该已经修复了，可以试试看
